name: Monitor de Loterias 15min

on:
  schedule:
    - cron: '*/15 * * * *' # Roda a cada 15 minutos
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para o robô salvar o arquivo JSON
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar Captura
        run: python main.py

      - name: Salvar alterações
        run: |
          git config --global user.name "Robo de Auditoria"
          git config --global user.email "bot@github.com"
          git add dados_loterias.json
          git commit -m "Atualização automática: $(date)" || echo "Sem mudanças"
          git push