name: Monitor de Loterias 15min

on:
  push:               # Aciona o robô toda vez que você salvar um arquivo
  schedule:
    - cron: '*/15 * * * *' # Roda automaticamente a cada 15 minutos
  workflow_dispatch:  # Mantém o botão de "Run workflow" ativo

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que o robô salve os ganhadores no JSON
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar Captura
        run: python main.py

      - name: Salvar alterações no Banco de Dados
        run: |
          git config --global user.name "Le - Auditoria"
          git config --global user.email "bot@github.com"
          git add dados_loterias.json
          git commit -m "Captura Automática: $(date)" || echo "Sem novos sorteios para registrar"
          git push origin main